### ISSUE TITLE
motion model xml template may be outdated

### ISSUE THREAD

**Issue by squishbug** [gtri/scrimmage#212]
Answer the following questions:

* what are you trying to do?

* what is the problem and how can it be recreated?

* what scrimmage commit are you on? You can see this with `git rev-parse HEAD`

* describe any changes you made to scrimmage.

* If you can recreate the issue using only plugins in the scrimmage repository, what mission file are you running?

**Comment by shaun-d-anderson** [comment]
Motion Model template has been addressed in recent commits.
