### ISSUE TITLE
No output generated if output type is summary

### ISSUE THREAD

**Issue by laurathepluralized** [gtri/scrimmage#23]
I realized today that, if I have `output_type` in my mission file set to `summary`, no results folder (i.e. ~/swarm-log/<timestamp_job_task> or ~/.scrimmage/logs/<timestamp_job_task>) gets created and no output files are generated. Results directory creation does still work if `output_type` is `frames` or `all`, and possibly others (haven't tested more options yet). The last time a mission file with `output_type` of `summary` generated results as expected was 11/16/2017.

**Comment by esquires** [comment]
Thanks for letting us know. This should now be fixed in 5b0673f
