### ISSUE TITLE
CV_BGR2GRAY and CV_LOAD_IMAGE_COLOR removed in latest OpenCV

### ISSUE THREAD

**Issue by palbers** [gtri/scrimmage#319]
When updating to the new scrimmage with the ground collision plugin, I get a compile error:

/scrimmage/src/plugins/interaction/MapGen2D/MapGen2D.cpp:115:37: error: use of undeclared identifier 'CV_LOAD_IMAGE_COLOR'
    map_img_ = cv::imread(filename, CV_LOAD_IMAGE_COLOR);
                                    ^
/scrimmage/src/plugins/interaction/MapGen2D/MapGen2D.cpp:180:29: error: use of undeclared identifier 'CV_BGR2GRAY'
    cv::cvtColor(img, gray, CV_BGR2GRAY);
                            ^
2 errors generated.

after some investigation, I uncovered this error:

$ cat imgcodecs_c.h
#error "This header with legacy C API declarations has been removed from OpenCV. Legacy contants are available from legacy/constants_c.h file."

When I re-installed scrimmage, Chris Richardsons brew install for the Mac updated boost, which updated OpenCV, which gave me the error above.  Others at MTIRE did not have that problem because they did not need to reinstall scrimmage when the ground collision update was installed.

**Comment by richardnnn** [comment]
This is due to OpenCv version issue, replacing following deprecated constants make code recompile for me:
Inside scrimmage/src/plugins/interaction/MapGen2D/MapGen2D.cpp, 
Line 115: change “CV_LOAD_IMAGE_COLOR” to “cv::IMREAD_COLOR” 
Line 180: Change “CV_BGR2GRAY” to “cv::COLOR_BGRA2GRAY”

**Comment by SyllogismRXS** [comment]
Thanks for the fix. I just submitted a pull request to incorporate these changes. When it passes the Travis-CI build/tests, I'll merge it into master: https://github.com/gtri/scrimmage/pull/333

**Comment by SyllogismRXS** [comment]
Resolved through https://github.com/gtri/scrimmage/pull/333
