### ISSUE TITLE
Cannot locate PyAutonomy 

### ISSUE THREAD

**Issue by richardnnn** [gtri/scrimmage#335]
Answer the following questions:

* what are you trying to do?
Run `scrimmage missions/python-test.xml`

* what is the problem and how can it be recreated?
The following error message is returned:
```
/.../scrimmage/build/plugin_libs/libPyAutonomy_plugin.dylib doesn't contain 'plugin_type'
ERROR: Could not locate scrimmage::Autonomy::PyAutonomy_plugin
VariableIO Error: no autonomies provide inputs required by Controller "SimpleAircraftControllerPID". Add VariableIO output declarations in as follows
First, include the VariableIO class in the cpp file: #include <scrimmage/common/VariableIO.h>
Second, place the following in its initializer:
```
And when I do `scrimmage-plugin PyAutonomy`:
```
==========================================
Plugin found.
Name: PyAutonomy
File: /.../scrimmage/include/scrimmage/plugins/autonomy/PyAutonomy/PyAutonomy.xml
Library: PyAutonomy_plugin
-------------------------
Params: XML_DIR=/.../scrimmage/include/scrimmage/plugins/autonomy/PyAutonomy/
XML_FILENAME=/.../scrimmage/include/scrimmage/plugins/autonomy/PyAutonomy/PyAutonomy.xml
class=AuctionAssign
library=PyAutonomy_plugin
module=auction_assign
/.../scrimmage/build/plugin_libs/libPyAutonomy_plugin.dylib doesn't contain 'plugin_type'
---------------------------
Matching plugin libraries found:
```
* what scrimmage commit are you on? You can see this with `git rev-parse HEAD`
Newest, 92e3153e2022ccd259a09e8a1ac8ca56b4af5d4c

* describe any changes you made to scrimmage.
Nothing

* If you can recreate the issue using only plugins in the scrimmage repository, what mission file are you running?
python-test.xml

**Comment by esquires** [comment]
Are you on OSX? We have only tested the python autonomy for Linux.

**Comment by richardnnn** [comment]
Yes I’m on OSX.

**Comment by aew61** [comment]
I am also having the exact same problem as above, but I am running Ubuntu 18 and python 3.6. Are there steps I can take to fix this?

**Comment by esquires** [comment]
It looks like that may be an old mission file. Does rlsimple.xml work for you?

**Comment by bobotran** [comment]
Is there a followup on this? I'm having the same issue.

**Comment by TheDash** [comment]
Also having this issue

**Comment by shaun-d-anderson** [comment]
With the addition of Variable-IO for controller and autonomy interaction the PyAutonomy plugin is deprecated and it is suggested to leverage the ROS integration which is supported in latest commits.
