### ISSUE TITLE
Execute "scrimmage ./missions/straight.xml" without GUI

### ISSUE THREAD

**Issue by BreederBai** [gtri/scrimmage#362]
ubuntu 16.04
![image](https://user-images.githubusercontent.com/27894314/65011321-bd18ca00-d945-11e9-928b-8aa63f08acff.png)

![image](https://user-images.githubusercontent.com/27894314/65010949-3fa08a00-d944-11e9-8f53-a468e2e16206.png)
What should I do to solve this problem?

**Comment by SyllogismRXS** [comment]
You need to install libvtk6-dev (Ubuntu Xenial) in order for the scrimmage viewer to be built. You can directly install VTK with the following command: sudo apt-get install libvtk6-dev. Then you need to run "cmake .." and "make in the scrimmage build directory again for cmake to find the newly installed VTK package. 

Based on the output of the install-binaries script, you may have some held debian packages. If you want to resolve that issue, you can manually try to install each of the packages listed (i.e., just try sudo apt-get install <package-name>, until you find the held package.) This may not be necessary depending on the plugins that you want to use.

**Comment by BreederBai** [comment]
@SyllogismRXS Thank you
