### ISSUE TITLE
GUI not showing when running mission

### ISSUE THREAD

**Issue by Juancw08** [gtri/scrimmage#372]
Answer the following questions:

Following tutorial and trying to run `scrimmage missions/straight.xml` but no GUI shows up.

git commit: a24dbe579b44707972fcaaa1bfc03601d4561d1f

No changes made to SCRIMMAGE

*I'm running straight.xml

**Comment by arschoon** [comment]
@Juancw08 How were you able to resolve the GUI not showing up? I am still having this issue.
