### ISSUE TITLE
Run number for batch runs

### ISSUE THREAD

**Issue by mjdebord** [gtri/scrimmage#393]
Answer the following questions:

* what are you trying to do?
Follow this tutorial on aggregating multi-run data
http://www.scrimmagesim.org/sphinx/html/tutorials/multiple-local-runs.html#aggregating-multi-run-data

* what is the problem and how can it be recreated?
I attempt to use scripts/BatchExample.ipynb to create the aggregate csv mentioned in the tutorial, However the notebook breaks in the first cell, I'm guessing because the file naming convention has changed compared to how the notebook attempts to read them.

I used the following command verbatim in order to create the batch run exeriments folder in .scrimmage/experiments
> ./run_experiments.py -t 100 -m ../missions/batch-example-mission.xml \
>   -p 7 -r ../config/ranges/batch-ranges.xml -n my_first_parameter_varying

The following two lines are from the first cell in the notebook

> files = glob.glob(os.path.join(log_dir, '\*\_job\_\*', 'cpa.csv')) # get folders with a cpa.csv in them?
> run_num = int((os.path.basename(os.path.dirname(file))).split('_')[-1]) # run number comes from folder name?

These lines make it seem that the folders are supposed to be named something like "[time]\_job\_[run number]", but the folders that I have appear to be in the format "[time]\_[worker id]". For example I have folders named "2019-11-07_11-13-15" that have an additional "\_[number 1-6]", where I am assuming the _[number 1-6] corresponds to a worker id (since I ran the command with 7 workers, if I run with 14 workers the files are named with _[number 1-13]). 

That said, I am unsure on how to actually recover the run number given one of the log folders. It doesn't seem to be given in any of the log files in the folder. For example, in the "batch_params.csv", there is a column called "run" with numbers 1-100 and the MS_gain and max_speed parameters for each run. How do I figure out which log folder corresponds to each of these runs?

* what scrimmage commit are you on? You can see this with `git rev-parse HEAD`
82d839a6b62ea5ea308a5947d5c09fbeca1619ce 

* describe any changes you made to scrimmage.
None

* If you can recreate the issue using only plugins in the scrimmage repository, what mission file are you running?
Just using the following command as given by the tutorial to create the experiments

> ./run_experiments.py -t 100 -m ../missions/batch-example-mission.xml \
>   -p 7 -r ../config/ranges/batch-ranges.xml -n my_first_parameter_varying

**Comment by shaun-d-anderson** [comment]
This issue has been addressed with most recent commit.
