### ISSUE TITLE
General Help related to the tool

### ISSUE THREAD

**Issue by ChoudharyNavit22** [gtri/scrimmage#406]
I am trying to make a scrimmage simulation related to herding mechanism using cars and drones, I am working with the most up to date scrimmage github commit, i went through all the tutorials and other stuff that was provided by you, the issue i am facing is as i am very new to this tool i am still not getting a very good understanding of the tool and so i am not able to proceed in the right direction with my project, so i wanted to know that is there any other reference materials i can go through or the projects that can help me understand how the tool works for writing custom plugins and trying out self made code for the scrimmage tool.

Any help regarding this would be very helpful for me!!

Thanks,

Regards,
Navit

**Comment by SyllogismRXS** [comment]
I added a new tutorial on how the capture the flag scenario was implemented in scrimmage. If you read the document and follow along with the provided code in scrimmage, it may be helpful:
http://www.scrimmagesim.org/sphinx/html/tutorials/capture-the-flag.html
