### ISSUE TITLE
There is a bug in the scrimmage-dependencies deb setup.sh file

### ISSUE THREAD

**Issue by TheDash** [gtri/scrimmage#422]
L#24: /opt/scrimmage/x86_64-linux-gnu/setup.sh

SCRIMMAGE_ROOT=/opt/scrimmage/x86_64-linux-gnu
export PATH=${SCRIMMAGE_ROOT}/bin:${PATH}
export JSBSIM_ROOT=${SCRIMMAGE_ROOT}/etc/JSBSim
export LD_LIBRARY_PATH=${SCRIMMAGE_ROOT}/lib:${LD_LIBRARY_PATH}
export CMAKE_PREFIX_PATH=${SCRIMMAGE_ROOT}:${CMAKE_PREFIX_PATH}

SCRIMMAGE_ROOT is not being exported which causes issues when trying to reference $(SCRIMAGE_ROOT) in any sort of env that needs to use it. For example, I was trying to use it to tell g++ where to find include files so I could build and link my plugin with scrimmage-core. The include files missing which alerted me to the issue were the google protobuf ones, which g++ was defaulting back to my system ones, giving me a warning that there was something going on here since scrimmage provided v3.3 of protobuf, but it wasn't being found because it was located in /opt/scrimmage/x86_64-linux-gnu/include

Could you add the fix to the deb and push a new one?

Thank you!

**Comment by SyllogismRXS** [comment]
I intentionally left the "SCRIMMAGE_ROOT" out of the export list to not clutter the user's environment unnecessarily. Are you using CMake to build your scrimmage plugins? If you use our reference CMake project (which is highly recommended), it will find scrimmage and the correct versions of protobuf and grpc automatically.

http://www.scrimmagesim.org/sphinx/html/tutorials/create-project.html
