### ISSUE TITLE
Tutorial for Multiple Runs fails because run_experiments.py has a hard coded path

### ISSUE THREAD

**Issue by tm132** [gtri/scrimmage#425]
Tutorial for Multiple Runs fails because run_experiments.py has a hard coded path for the default ranges file, which makes assumptions about the execution environment that are likely to be wrong.

-+-

Running through the tutorial, on the multiple runs page:
http://www.scrimmagesim.org/sphinx/html/tutorials/multiple-local-runs.html

I ran this command straight out of the tutorial:
```
$ ./run_experiments.py -t 100 -m ../missions/straight-vs-motorschemas.xml -p 7
```
Which gave me the error:
```
$ ./run_experiments.py -t 100 -m ../missions/straight-vs-motorschemas.xml -p 7
Ranges file does not exist... Exiting
```

Looking at the code in run_experiments.py, we have:
```
parser.add_argument('-r', '--ranges', help='Ranges file for generating new'
                    ' scenarios', default= "~/scrimmage/scrimmage/config/ranges/batch-ranges.xml")
[...]
args = parser.parse_args()
[...]
# See if the user is using the ranges file
if not args.ranges:
    print('not using ranges file')
elif not os.path.exists(os.path.expanduser(args.ranges)):
    sys.exit('Ranges file does not exist... Exiting')
```

The default ranges path seems to make some assumptions about the environment. Perhaps it should say `' scenarios', default= "../config/ranges/batch-ranges.xml")`, which works for me. The tutorial does say to go into the scripts directory before executing the above command (
`$ cd ~/scrimmage/scrimmage/scripts`), so I think it's fine to assume this to be the current path for someone who is at this point in the tutorial.

-+-

I am running on a VirtualBox VM (virtual box 6.0.14)
Host Machine OS: Windows 10
VM OS: Ubuntu 18.04.4 LTS
Python Version: Python 3.7.3 (default, Mar 27 2019, 22:11:17) 

I am on SCRIMMAGE branch `master`, commit `eb1cc29d072decefeea1792cf0bb2aaeb56367ea`.

My path to scrimmage is:
`/home/user/sandbox/project/scrimmage`

**Comment by shaun-d-anderson** [comment]
Tutorial directions have been updated to reflect latest commit, and fix issue.
