### ISSUE TITLE
doesn't run setup.sh.in while setting up in linux machine

### ISSUE THREAD

**Issue by sbyebss** [gtri/scrimmage#474]
* what are you trying to do?

  I am trying to [Setup SCRIMMAGE/AirSim on my Linux machine.](http://www.scrimmagesim.org/sphinx/html/tutorials/airsim-plugin.html#setup-scrimmage-airsim-on-your-linux-machine) 
 
* what is the problem and how can it be recreated?

    I followed all commands and finally run `source ~/.scrimmage/setup.bash` but in terminal, it shows `~/.scrimmage folder doesn't exist`.  I think the problem is it didn't run [setup.sh.in](https://github.com/gtri/scrimmage/blob/0861cdc21d39c9a662fc818a4d73f48081b64017/3rd-party/packages/scrimmage-dependencies/scrimmage-dependencies/scripts/setup.sh.in). Do you know why the previous commands skip this setup.sh.in?

* what scrimmage commit are you on? You can see this with `git rev-parse HEAD`

   2142936b6722b7e20b77cc71975d102106277958

* describe any changes you made to scrimmage.

  I manually create `${HOME}/.scrimmage/setup.bash` and echo the code into this file.

**Comment by SyllogismRXS** [comment]
Those instructions might be slight out of date or they assumed you had already built scrimmage at some point. You need to run the "cmake .." command in the build directory before the ~/.scrimmage/setup.bash file is generated. I recommend building scrimmage based on the main README's instructions first (https://github.com/gtri/scrimmage#build-scrimmage), then to build the AirSim plugin, you can look at the additional steps in the tutorials.

**Comment by sbyebss** [comment]
okay, thanks! The README and the document are different. Get it.
