### ISSUE TITLE
Drawing on 2D HUD

### ISSUE THREAD

**Issue by stoplime** [gtri/scrimmage#488]
Feature request:
There is no library for creating drawing or text onto the HUD(heads up display, or overlay on the camera). Currently there is only the current time and the time multiplier displayed on the bottom of the screen but a library to allow more to be added would be nice to have for mission specific information to be displayed. Using a 2D screen coordinate system would be helpful for displaying text such as real-time metrics onto the screen rather than having to rely on creating floating text in the simulation.

**Comment by frazierbaker** [comment]
We are looking at using CesiumJS or some other technology to do an overhaul of the viewer.  We will look into providing a HUD interface then and keep you in the loop.  For now I'm closing this.
