### ISSUE TITLE
Real-Time User Input Library

### ISSUE THREAD

**Issue by stoplime** [gtri/scrimmage#493]
Feature request: (May not be inline with the scrimmage philosophy)
Have a library that accepts user input whether that be a keyboard input control or a joystick or maybe even a radio control adapter to allow for the simulated crafts be controlled by the user. This could be useful for debugging purposes and for higher fidelity testing with a pilot on hand to take over scenarios.

**Comment by mday299** [comment]
SCRIMMAGE is more of an autonomy tool, not a flight sim.  Can you not do this with X-Plane, MS Flight Sim, FlghtGear  etc.  If you'd like user input controls, you are welcome to develop a SCRIMMAGE plugin to accomodate this.
