### ISSUE TITLE
Window Params on Startup

### ISSUE THREAD

**Issue by stoplime** [gtri/scrimmage#494]
Low priority
Feature request:
Have a tag in the scrimmage mission xml that can define the simulation window size on startup. A fullscreen option would also be nice to have.

**Comment by frazierbaker** [comment]
Full Screen already exists as an option in the mission file: https://www.scrimmagesim.org/sphinx/html/overview/xml-tags.html?highlight=full%20screen

If you feel that more fine-grain control of window size is needed, we welcome a PR.
