### ISSUE TITLE
AirSimSensor: ROSAirSim Plugin not found

### ISSUE THREAD

**Issue by nrakoski3** [gtri/scrimmage#498]
Answer the following questions:

* what are you trying to do?
Run the SCRIMMAGE/ AirSim simulation with ROS. The simulation with ROS will not run, however the plugin-manager does find the plugin as evidence by the scrimmage-plugin tool. When you run "**scrimmage-plugin ROSAirSim**" it returns that it found the plugin.

* what is the problem and how can it be recreated?
To recreate you will need to complete the SCRIMMAGE/ AirSim setup. https://www.scrimmagesim.org/sphinx/html/tutorials/airsim-plugin.html#publish-data-to-ros
Build and run with ROS the quad-airsim-ex1.xml mission. Make sure to go inside the mission, uncomment the ROSAirSim plugin. Don't uncomment any other ROS plugins.

* what scrimmage commit are you on? You can see this with `git rev-parse HEAD`
The current master branch HEAD: 66f3a13faae5b930bdc85a131b6e5175d254d7bf

* describe any changes you made to scrimmage.
quad-airsim-ex1.xml with the ROSAirSim plugin uncommented.

* If you can recreate the issue using only plugins in the scrimmage repository, what mission file are you running?
quad-airsim-ex1.xml with the ROSAirSim plugin uncommented.

**Temporary Fix for Others Seeing this Issue:**
If you are trying to use the SCRIMMAGE/ AirSim with ROS simulation and you see this issue. Checkout the following scrimmage master commit instead of the current master HEAD and the simulation with ROS will be operable: ad18e6c2a7ea01de822325745d9a247ffad51d08

**Comment by frazierbaker** [comment]
Closing because of #500
