### ISSUE TITLE
Network/Port Problems

### ISSUE THREAD

**Issue by lvalcourt** [gtri/scrimmage#59]
E0507 09:47:17.695580374   13049 server_chttp2.c:53]         {"created":"@1525700837.693440183","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.c","file_line":259,"referenced_errors":[{"created":"@1525700837.693434142","description":"Unable to configure socket","fd":3,"file":"src/core/lib/iomgr/tcp_server_posix.c","file_line":388,"referenced_errors":[{"created":"@1525700837.693421340","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_posix.c","file_line":362,"os_error":"Address already in use","syscall":"bind"}]}]}

I always get this error when trying to run the test_openai.py file. I have tried using the original code (TutorialOpenAI, RLSimple, SimpleLearner from the tutorial) and also I created one of my own but with no avail. None of the created scripts actually runs, either it stays and Simulation Complete or it says 100% at the end of the terminal.

**Comment by esquires** [comment]
Solved offline. The solution was to close down existing instances of "test_openai.py"

```[bash]
cd scrimmage
git fetch
git checkout e2d6906 # this will checkout the latest master as of this morning

# this will probably show something (see https://askubuntu.com/a/538209)
netstat -tulnp | grep 50051

# this should make sure that existing instances are closed
pkill -9 -f scrimmage
pkill -9 -f test_openai

 
# this will probably now not show something
netstat -tulnp | grep 50051

 
# this line will test that your python installation is working.
# it should not give any messages about not being able to
# open openai or grpc
python -c 'import scrimmage'

python test/test_openai.py
```
