### ISSUE TITLE
MoveToGoalMS goal Parsing Inconsistency

### ISSUE THREAD

**Issue by gtcooke94** [gtri/scrimmage#78]
In some uses of MoveToGoalMS, the goal in defined in the mission xml file as `goal='x y z'`. This causes the params dictionary to just contain goal: x, which then causes the goal to be defined as the default 0,0,0 definition. In other cases in the mission xml file, goal  is defined as `goal='x,y,z'`. This works correctly with the parsing written in MoveToGoalMS and causes the goal to be correctly set.
It seems that the easiest approach is just adding commas to the mission files that aren't being parsed correctly, but since a recent commit just changed the parsing code I wanted to make sure this wasn't a potential change to the parsing that would affect other plugins too.
An example that fails can be seen here:
`include/scrimmage/plugins/autonomy/MotorSchemas/MotorSchemas.xml:14:    [ MoveToGoalMS gain='1.0' use_initial_heading='true' goal='100 0 0']`

**Comment by SyllogismRXS** [comment]
With the current XML parsing code, we can't have spaces in a vector that is within a vector (the goal vector within the brackets [ ]). I've added a warning message to MoveToGoalMS when the goal isn't parsed correctly and now we have to specify goal='100,0,0'.
