### ISSUE TITLE
Multi-Agent Simulation

### ISSUE THREAD

**Issue by lvalcourt** [gtri/scrimmage#80]
To my understanding, by having mutliple actors set up, each actor will run its own instance of autonomy. Moving forward to the script, I get each actor new state given a respective action from the environment. On the other hand, I receive a reward that reflects the reward of both actors. 
I want to share information between multiple actors while they run in the same environment, is this possible?

Thanks for the help!

**Comment by esquires** [comment]
This seems like it was solved in #81. Can I close this?

**Comment by lvalcourt** [comment]
Yes, it resolve now.

Thanks for the help,

Luis
